import Header from '@/component/header/header';
import './globals.css';
import { SessionProvider } from 'next-auth/react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionProvider>
        <body>
          <Header />
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
